### PR TITLE
AppIcons (small, large and source file)

### PR DESCRIPTION
**Pull request by crxdelsol**
- Added small AppIcon with parallax effect
- Added large AppIcon with parallax effect
- Added original .sketch file with both icon sources

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
@crxdelsol @FrnklyN, @jordibruin, and @matthijst, thanks for taking the time to create an App Icon! @basvroegop and @rmens, thanks for getting the ball rolling on this, much appreciated. 

@rmens, since you have such a nicely filled up Apple TV home screen, could you install the current version of the app on your device and create a screenshot with the app's icon in the middle to put in the [screenshots directory](https://github.com/jeffkreeftmeijer/UitzendingGemist/tree/master/Screenshots) and the README?

**Comment by basvroegop** [comment]
Screenshot, as requested via Twitter: 

http://imgur.com/bbRfZfx

**Comment by FrnklyN** [comment]
@basvroegop The orange looks a bit cheap. Maybe a little gradient can change that.

**Comment by basvroegop** [comment]
Not my logo, just provided the screenshot. Other people @jeffkreeftmeijer mentioned made it.

**Comment by FrnklyN** [comment]
@basvroegop I know, but what is your opinion on that?

**Comment by basvroegop** [comment]
@FrnklyN Color is a bit lighter than the original NPO logo. http://www-assets.npo.nl/assets/npo_logo-c0f9cdc10f5633cc362e5b8113a3350e.png 

But tbh, I prefer the lighter one myself.

**Comment by jeffkreeftmeijer** [comment]
@FrnklyN  as this pull request is already merged, could you create a new issue (or send a new pull request) to discuss this?

**Pull request merged**
